create sequence hibernate_sequence start with 1 increment by 1;
create table superheroes (id bigint not null, created_date timestamp, name varchar(255), primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table superheroes (id bigint not null, created_date timestamp, name varchar(255), primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table superheroes (id bigint not null, created_date timestamp, name varchar(255), primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table superheroes (id bigint not null, created_date timestamp, name varchar(255), primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table superheroes (id bigint not null, created_date timestamp, name varchar(255), primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table superheroes (id bigint not null, created_date timestamp, name varchar(255), primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table superheroes (id bigint not null, created_date timestamp, name varchar(255), primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table superheroes (id bigint not null, created_date timestamp, name varchar(255), primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table superheroes (id bigint not null, created_date timestamp, name varchar(255), primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table superheroes (id bigint not null, created_date timestamp, name varchar(255), primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table superheroes (id bigint not null, created_date timestamp, name varchar(255), primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table superheroes (id bigint not null, created_date timestamp, name varchar(255), primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table superheroes (id bigint not null, created_date timestamp, name varchar(255), primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table superheroes (id bigint not null, created_date timestamp, name varchar(255), primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table superheroes (id bigint not null, created_date timestamp, name varchar(255), primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table superheroes (id bigint not null, created_date timestamp, name varchar(255), primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table superheroes (id bigint not null, created_date timestamp, name varchar(255), primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table superheroes (id bigint not null, created_date timestamp, name varchar(255), primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table superheroes (id bigint not null, created_date timestamp, name varchar(255), primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table superheroes (id bigint not null, created_date timestamp, name varchar(255), primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table superheroes (id bigint not null, created_date timestamp, name varchar(255), primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table superheroes (id bigint not null, created_date timestamp, name varchar(255), primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table superheroes (id bigint not null, created_date timestamp, name varchar(255), primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table superheroes (id bigint not null, created_date timestamp, name varchar(255), primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table superheroes (id bigint not null, created_date timestamp, name varchar(255), primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table superheroes (id bigint not null, created_date timestamp, name varchar(255), primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table superheroes (id bigint not null, created_date timestamp, name varchar(255), primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table superheroes (id bigint not null, created_date timestamp, name varchar(255), primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table superheroes (id bigint not null, created_date timestamp, name varchar(255), primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table superheroes (id bigint not null, created_date timestamp, name varchar(255), primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table superheroes (id bigint not null, created_date timestamp, name varchar(255), primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table superheroes (id bigint not null, created_date timestamp, name varchar(255), primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table superheroes (id bigint not null, created_date timestamp, name varchar(255), primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table superheroes (id bigint not null, created_date timestamp, name varchar(255), primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table superheroes (id bigint not null, created_date timestamp, name varchar(255), primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table superheroes (id bigint not null, created_date timestamp, name varchar(255), primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table superheroes (id bigint not null, created_date timestamp, name varchar(255), primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table superheroes (id bigint not null, created_date timestamp, name varchar(255), primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table superheroes (id bigint not null, created_date timestamp, name varchar(255), primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table superheroes (id bigint not null, created_date timestamp, name varchar(255), primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table superheroes (id bigint not null, created_date timestamp, name varchar(255), primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table superheroes (id bigint not null, created_date timestamp, name varchar(255), primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table superheroes (id bigint not null, created_date timestamp, name varchar(255), primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table superheroes (id bigint not null, created_date timestamp, name varchar(255), primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table SUPERHEROES (id bigint not null, created_date timestamp, name varchar(255), primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table SUPERHEROES (id bigint not null, created_date timestamp, name varchar(255), primary key (id));
create sequence hibernate_sequence start with 1 increment by 1;
create table SUPERHEROES (id bigint not null, created_date timestamp, name varchar(255), primary key (id));
create table SUPERHEROES (id bigint generated by default as identity, created_date timestamp, name varchar(255), primary key (id));
create table SUPERHEROES (id bigint generated by default as identity, created_date timestamp, name varchar(255), primary key (id));
create table SUPERHEROES (id bigint generated by default as identity, created_date timestamp, name varchar(255), primary key (id));
create table SUPERHEROES (id bigint generated by default as identity, created_date timestamp, name varchar(255), primary key (id));
create table superheroes (id bigint generated by default as identity, created_date timestamp, name varchar(255), primary key (id));
create table superheroes (id bigint generated by default as identity, created_date timestamp, name varchar(255), primary key (id));
create table superheroes (id bigint generated by default as identity, created_date timestamp, name varchar(255), primary key (id));
create table superheroes (id bigint generated by default as identity, created_date timestamp, name varchar(255), primary key (id));
create table superheroes (id bigint generated by default as identity, created_date timestamp, name varchar(255), primary key (id));
create table superheroes (id bigint generated by default as identity, created_date timestamp, name varchar(255), primary key (id));
create table superheroes (id bigint generated by default as identity, created_date timestamp, name varchar(255), primary key (id));
create table superheroes (id bigint generated by default as identity, created_date timestamp, name varchar(255), primary key (id));
create table superheroes (id bigint generated by default as identity, created_date timestamp, name varchar(255), primary key (id));
create table superheroes (id bigint generated by default as identity, created_date timestamp, name varchar(255), primary key (id));
create table superheroes (id bigint generated by default as identity, created_date timestamp, name varchar(255), primary key (id));
create table superheroes (id bigint generated by default as identity, created_date timestamp, name varchar(255), primary key (id));
create table superheroes (id bigint generated by default as identity, created_date timestamp, name varchar(255), primary key (id));
create table superheroes (id bigint generated by default as identity, created_date timestamp, name varchar(255), primary key (id));
create table superheroes (id bigint generated by default as identity, created_date timestamp, name varchar(255), primary key (id));
create table superheroes (id bigint generated by default as identity, created_date timestamp, name varchar(255), primary key (id));
create table superheroes (id bigint generated by default as identity, created_date timestamp, name varchar(255), primary key (id));
